### ISSUE TITLE
Guide on how to create and publish openml-python extensions

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#771] opened 2019-08-20 15:19 UTC
* Rip out everything except the extension class which extends the interface
* Register the extension: https://openml.github.io/openml-python/master/generated/openml.extensions.register_extension.html#openml.extensions.register_extension
* Set up openml-python extensions organization
* Unit tests: every new repo need to set up own CI
* Documentation: also local?

**Comment by mfeurer** [comment] 2019-08-20 15:22
Duplicate of #730.

**Closed by mfeurer** 2019-08-20 15:22 UTC
