### ISSUE TITLE
Issues instantiating models from runs 

### ISSUE THREAD

**Issue by hp2500** [openml/openml-python#720] opened 2019-06-26 15:20 UTC
Hi there, I am running into problems when I am trying to initialize models from older runs. Here is an example with a run I created yesterday. 
![image](https://user-images.githubusercontent.com/27285925/60192140-68145e80-9803-11e9-9980-43bf0376017a.png)
As you see it works perfectly fine. 

However, when I am trying to initialize an older run (from 2016), I am getting this error:
![image](https://user-images.githubusercontent.com/27285925/60192648-35b73100-9804-11e9-8f51-014c41be71e5.png)

This might be related to the issue I recently raised about initializing models from flows  (#718).
Is there anything I am missing, or are the older runs simply not compatible with the initialize_model_from_run function?

@amueller

**Comment by hp2500** [comment] 2019-06-26 15:31
Update: I have played around with different runs and I am now able to produce the same error that I was getting when trying to reinstantiate a model from flows (#718). 

i.e. ValueError: Trying to deserialize a model with dependency sklearn==0.18.1 not satisfied.
So it seems to be the same issue. 

@amueller

**Comment by amueller** [comment] 2019-06-27 19:53
```python
print("this looks nice")
```

**Comment by mfeurer** [comment] 2019-07-08 13:20
Closing this as it appears to have the same root cause as #718 and will therefore be fixed by #722, too.

**Closed by mfeurer** 2019-07-08 13:20 UTC
