### ISSUE TITLE
openml.runs.get_run throws error ""TypeError: list indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by sagar-nyamagouda** [openml/openml-python#1161] opened 2022-09-12 04:50 UTC
#### Description
get_run(int) or get_runs(list[int) function throws error "TypeError: list indices must be integers or slices, not str"

#### Steps/Code to Reproduce
Example:
```python
import openml
openml.runs.get_run(1)
openml.runs.get_runs([1,2,3]
```
#### Expected Results
Should return OpenMl run results

#### Actual Results
File "gbls.py", line 33, in main
    run_output = openml.runs.get_run(1, ignore_cache = True)
  File "/usr/local/lib/python3.6/site-packages/openml/runs/functions.py", line 735, in get_run
    run = _create_run_from_xml(run_xml)
  File "/usr/local/lib/python3.6/site-packages/openml/runs/functions.py", line 813, in _create_run_from_xml
    dataset_id = int(run["oml:input_data"]["oml:dataset"]["oml:did"])
TypeError: list indices must be integers or slices, not str

#### Versions

Linux-3.10.0-514.el7.x86_64-x86_64-with-centos-7.3.1611-Core
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
NumPy 1.19.5
SciPy 1.5.4
Scikit-Learn 0.24.2
OpenML 0.12.2

**Comment by PGijsbers** [comment] 2022-09-12 08:17
Thanks for reporting the issue. This seems to be a duplicate of #1102.

**Closed by PGijsbers** 2022-09-12 08:17 UTC
