### ISSUE TITLE
Dataset processed with error

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#610] opened 2019-01-10 14:40 UTC
#### Description
While trying to get a task, the following error happened:
 
`OpenMLServerException: https://www.openml.org/api/v1/xml/data/features/1176 returned code 274: No features found.  Additionally, dataset processed with error
`

The dataset that the task is built on is deactivated, however there are about 25k runs.
Is this the expected behaviour?

#### Steps/Code to Reproduce
```openml.tasks.get_task(6566)```

#### Expected Results
The task info.

@mfeurer @janvanrijn

**Comment by PGijsbers** [comment] 2019-03-18 10:19
Looks like a duplicate of #594. Feel free to re-open if you disagree.

**Closed by PGijsbers** 2019-03-18 10:19 UTC
