### ISSUE TITLE
Can't upload run

### ISSUE THREAD

**Issue by kazeevn** [openml/openml-python#71] opened 2016-03-15 16:59 UTC
Get code 450, using Python 3.5.1 on Anaconda.

[covtype.zip](https://github.com/openml/openml-python/files/174391/covtype.zip)

**Comment by amueller** [comment] 2016-03-18 14:04
still?

**Comment by mfeurer** [comment] 2017-02-01 13:42
I assume this is a duplicate of #186, therefore I assign this to @janvanrijn

**Comment by janvanrijn** [comment] 2017-03-03 12:35
I would assume that this is solved, the issue comes from before the bug refactoring. Will check so when back in Freiburg.

**Comment by janvanrijn** [comment] 2017-03-17 16:18
I think this issue can be closed, the code in the notebook is clearly from an older version of the api connector. 

@kazeevn Sorry that this took so long

**Closed by janvanrijn** 2017-03-17 16:18 UTC
