### ISSUE TITLE
Allow several instances of same flow within one flow

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#826] opened 2019-10-15 08:52 UTC
Right now we can't have more than one scaler or imputer in a pipeline/column transformer.
@mfeurer has some work-arounds (creating new classes for second instances) but that's a hassle and means that we'll have different flows for essentially the same step.

**Comment by mfeurer** [comment] 2019-10-15 12:22
This is a duplicate of #638 (I will reopen the original one instead) and actually an upstream issue discussed in https://github.com/openml/OpenML/issues/340

**Closed by mfeurer** 2019-10-15 12:22 UTC
