### ISSUE TITLE
support string data

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#343] opened 2017-10-10 16:14 UTC
```python
import openml
openml.datasets.get_dataset(40753)
```
```
---------------------------------------------------------------------------
PyOpenMLError                             Traceback (most recent call last)
<ipython-input-49-8a4438c37ec6> in <module>()
----> 1 asdf.get_data()

~/checkout/openml-python/openml/datasets/dataset.py in get_data(self, target, target_dtype, include_row_id, include_ignore_attributes, return_categorical_indicator, return_attribute_names)
    202 
    203         if not self._data_features_supported():
--> 204             raise PyOpenMLError('Dataset not compatible, PyOpenML cannot handle string features')
    205 
    206         path = self.data_pickle_file

PyOpenMLError: Dataset not compatible, PyOpenML cannot handle string features

```

**Comment by mfeurer** [comment] 2017-10-10 16:22
That's a duplicate of #257.

**Closed by mfeurer** 2017-10-10 16:22 UTC

**Comment by amueller** [comment] 2017-10-10 16:32
sorry for the duplicate.
