### ISSUE TITLE
python 2.7, openml 060 / datasets / datasets.py assertion, special openml-datasets

### ISSUE THREAD

**Issue by bstrang** [openml/openml-python#375] opened 2017-11-16 07:08 UTC
For some openml tasks (e.g. tid=3512), datasets.py.get_features_by_type() raises an assertion-error,
"row id should be a str".

Maybe a unicode vs. str type issue - special to python 2.7.?
(Issue does not occure  when using python 3.6)

[Issue Row-id-unicode-vs-string.zip](https://github.com/openml/openml-python/files/1477606/Issue.Row-id-unicode-vs-string.zip)

**Comment by mfeurer** [comment] 2017-11-17 09:19
Thanks a lot for reporting this. For the reference, this is the code to reproduce this issue in python2.7:
```
import sys
import openml

print sys.version_info
print 'OpenML version: ', openml.__version__

task_id = 3
print 'task_id', task_id

task = openml.tasks.get_task(task_id)
indices = task.get_dataset().get_features_by_type(data_type='nominal')
print

task_id = 3512
print 'task_id', task_id

task = openml.tasks.get_task(task_id)
indices = task.get_dataset().get_features_by_type(data_type='nominal')
print
```

Do you want to contribute to the package and try to work on a fix for this?

**Comment by janvanrijn** [comment] 2017-11-17 10:07
Thanks for reporting this, I created a PR.

**Comment by mfeurer** [comment] 2018-03-19 14:40
This appears to be fixed since November last year.

**Closed by mfeurer** 2018-03-19 14:40 UTC
