### ISSUE TITLE
Klaverjas Dataset

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#616] opened 2019-02-13 11:37 UTC
#### Description

Get data fails while trying to retrieve the examples and labels of the Klaverjas dataset.
#### Steps/Code to Reproduce
```python
import openml

task = openml.tasks.get_task(168739)

dataset = task.get_dataset()

x, y, categorical = dataset.get_data(
    target=dataset.default_target_attribute,
    return_categorical_indicator=True
)
```
#### Actual Results
Dataset 41228 not compatible, PyOpenML cannot handle string features

**Comment by mfeurer** [comment] 2019-02-13 11:47
That's a duplicate of #257, closing this. It might be added via #548.

**Closed by mfeurer** 2019-02-13 11:47 UTC

**Comment by janvanrijn** [comment] 2019-02-13 12:54
For this particular dataset, the string attribute (sh/c)ould be ignored
