### ISSUE TITLE
Datasets with a date feature fail to load

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#1113] opened 2021-09-10 18:31 UTC
#### Description
Some datasets have a 'date' type feature, e.g.:
https://www.openml.org/data/download/21377734/FOREX_eurchf-minute-Close.arff

When downloading them with get_dataset(id), we get an error:
Bad @ATTRIBUTE type, at line 2.

The error is raised by the liac-arff library. Very likely this is the same issue:
https://github.com/renatopp/liac-arff/issues/121

It's not clear whether this will be tackled anytime soon.
Should we just let this fail or produce a nicer error message? Or live with this until we can move to Parquet?

#### Steps/Code to Reproduce
```python
import openml
openml.datasets.get_dataset(41708)
```

#### Expected Results
A loaded dataset or an informative error message

#### Actual Results
Bad @ATTRIBUTE type, at line 2.

**Comment by mfeurer** [comment] 2021-09-11 10:14
> The error is raised by the liac-arff library. Very likely this is the same issue:

Yes, it is.

> It's not clear whether this will be tackled anytime soon.

There is a stalled PR in the liac-arff repo, so if someone has time they can pick it up.

> Or live with this until we can move to Parquet?

That was my plan so far.

**Comment by mfeurer** [comment] 2021-09-11 10:16
Closing this as a duplicate of #942.

**Closed by mfeurer** 2021-09-11 10:16 UTC
