### ISSUE TITLE
get_dataset doesnt work for sparse datasets

### ISSUE THREAD

**Issue by sahithyaravi1493** [openml/openml-python#814] opened 2019-10-14 07:33 UTC
#### Description
Categorical data needs to be numeric when using sparse ARFF.
Datasets: 392, 395, etc....

#### Expected Results
No error is thrown. 

#### Actual Results
Traceback (most recent call last):
  File "c:\users\s164255\documents\openml-python\openml\datasets\dataset.py", line 328, in _parse_data_from_arff
    np.array(type_, dtype=np.float32)
ValueError: could not convert string to float: '6-Ketoprostaglandin-F1-alpha'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\dash\dash.py", line 1289, in dispatch
    response.set_data(self.callback_map[output]['callback'](*args))
  File "C:\Users\s164255\anaconda3\envs\openml.org\lib\site-packages\dash\dash.py", line 1173, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "C:\Users\s164255\Documents\openml.org\src\dash\callbacks.py", line 39, in render_layout
    layout, df = get_layout_from_data(data_id)
  File "C:\Users\s164255\Documents\openml.org\src\dash\layouts.py", line 36, in get_layout_from_data
    df, metadata, numerical_data, nominal_data, name = get_data_metadata(data_id)
  File "C:\Users\s164255\Documents\openml.org\src\dash\helpers.py", line 24, in get_data_metadata
    data = datasets.get_dataset(data_id)
  File "c:\users\s164255\documents\openml-python\openml\datasets\functions.py", line 519, in get_dataset
    description, features, qualities, arff_file
  File "c:\users\s164255\documents\openml-python\openml\datasets\functions.py", line 1007, in _create_dataset_from_description
    qualities=qualities,
  File "c:\users\s164255\documents\openml-python\openml\datasets\dataset.py", line 171, in __init__
    self.data_pickle_file = self._create_pickle_in_cache(data_file)
  File "c:\users\s164255\documents\openml-python\openml\datasets\dataset.py", line 411, in _create_pickle_in_cache
    X, categorical, attribute_names = self._parse_data_from_arff(data_file)
  File "c:\users\s164255\documents\openml-python\openml\datasets\dataset.py", line 331, in _parse_data_from_arff
    "Categorical data needs to be numeric when "
ValueError: Categorical data needs to be numeric when using sparse ARFF.

**Comment by mfeurer** [comment] 2019-10-14 07:35
I believe this is a duplicate of #758, please reopen if that's not the case.

**Closed by mfeurer** 2019-10-14 07:35 UTC
Labels: priority
