### ISSUE TITLE
Issues instantiating/running models from flows

### ISSUE THREAD

**Issue by hp2500** [openml/openml-python#718] opened 2019-06-20 03:57 UTC
Hi there, 

I am trying to use a flow to instantiate a sklearn model that can then be run on a task. From the documentation it seems like this should be possible in several different ways, but haven't had any success so far trying to get a model from a flow with flow_to_model or from a setup with initialize_model. 
![image](https://user-images.githubusercontent.com/27285925/59817431-cf0ab280-92ed-11e9-81f2-ce8efe853ff2.png)

Running a flow directly on a task doesn't seem to work either.
![image](https://user-images.githubusercontent.com/27285925/59816887-c618e180-92eb-11e9-8be7-b3456a44b38c.png)
Do you have any suggestions?

@amueller

**Comment by PGijsbers** [comment] 2019-06-25 13:21
Sorry for the delay.
To reproduce the issue, please let us know which flow and/or setup you are working with.

That said, running a flow on a task is easiest done in the following way (e.g. `task 3` and `flow 7684`):

```python
import openml

task = openml.tasks.get_task(3)
flow = openml.flows.get_flow(7684, reinstantiate=True)  # Necessary otherwise no model is made.

run = openml.runs.run_flow_on_task(flow, task)
```
Note the one line in the middle, where the model is reinstantiated after downloading the flow. I think it's fair to say that we should check for this automatically in the `run_flow_on_task` method.

**Comment by hp2500** [comment] 2019-06-25 15:53
Hi, thanks a lot for your reply! I have tried your code, but it seems to require an older sklearn version. 

![image](https://user-images.githubusercontent.com/27285925/60113096-0e4a6080-973f-11e9-803f-cf5a4c10e4b1.png)

I am using sklearn version 0.21.2, because I am interested in some functions that were added only recently. Do you think there is a workaround? 

P.S. I originally used flow #6970, but I don't think it matters because I am getting the same errors for different flow ids. 

@amueller

**Comment by hp2500** [comment] 2019-06-25 15:56
But maybe, the required sklearn version depends on which version was used in the original flow... When I try a different flow, the error mentions a different sklearn version. 

![image](https://user-images.githubusercontent.com/27285925/60113614-2bcbfa00-9740-11e9-8975-b9afc814170d.png)

@amueller

**Comment by PGijsbers** [comment] 2019-06-25 19:53
Yes, that is the case. The flows require a specific `scikit-learn` version to ensure reproducibility. I don't believe there currently is a way to automatically create a new flow for your scikit-learn version based on a flow-id and your current environment (or find one on the server that matches). I can understand this would be a desirable feature, which for pure-scikit-learn based flows should be feasible.

A little disclaimer, I was not involved at the time this flow (6970) was created or the related study (study14) was done. With that said, it looks like the flow you are trying to deserialize (6970) in particular also relies on non-scikit-learn components (`openmlstudy14.preprocessing.ConditionalImputer`). I don't currently know the status of reproducing that scenario, perhaps @mfeurer knows. I image you need to make sure the original source code can be found (https://github.com/openml/Study-14), which @janvanrijn should be more familiar with.

**Comment by amueller** [comment] 2019-06-27 19:10
@PGijsbers Thanks for all the replies! It would be great to do the instantiation automatically for ``run_flow_on_task``. I couldn't find that in the documentation and the error message is not very helpful. Maybe either you or @hp2500 can just add this to the error message for now.

I don't think instantiating Study-14 pipelines should be a high priority (there is no setup.py). We were actually more interested in getting the parameters of the last pipeline step. To do that, we could in principle just use mocking to replace the ContitionalImputer just so we can call ``pipeline[-1].get_params()``. But maybe that's to specialized.

More generally I think it would be good to optionally disable the version check if the libraries are available.

**Comment by PGijsbers** [comment] 2019-06-28 09:35
I'll make the change to automatically reinstantiate the model when `run_flow_on_task` is called with a flow that has no instantiated model and all dependencies are satisfied (with the right version). I think we should involve @mfeurer on if/how/when we want to allow disabling version checks and how it should behave.

**Comment by mfeurer** [comment] 2019-07-08 12:25
> More generally I think it would be good to optionally disable the version check if the libraries are available.

We could create different levels of checks for this:

* that the library is available
* that the major version is equal
* that the minor version is equal
* that the exact version is equal

Would this together with #722 solve this issue?

**Comment by mfeurer** [comment] 2019-07-09 13:27
Fixed via #724. Please reopen if that's not the case.

**Comment by amueller** [comment] 2019-07-22 18:59
```python
import openml

task = openml.tasks.get_task(3)
flow = openml.flows.get_flow(7684, reinstantiate=True)  # Necessary otherwise no model is made.

run = openml.runs.run_flow_on_task(flow, task)
```
yields

> ValueError: Trying to deserialize a model with dependency sklearn==0.19.1 not satisfied.

**Comment by mfeurer** [comment] 2019-07-23 08:49
@amueller will you have a look into this or should I ask @Neeratyoy to check this?

**Closed** 2019-09-26 09:02 UTC
