### ISSUE TITLE
Better error message if login failed

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#32] opened 2016-02-12 11:22 UTC
If you use a faulty api key, the package stays silent, until you try to download something, at which point it 
returns a HTTP 500 Error. I believe this happened because my api key included a newline at the end.

Can we either check the login after creating the API connector, or return a proper error message?

```
/usr/local/lib/python2.7/site-packages/openml-0.0.1.dev0-py2.7.egg/openml/apiconnector.pyc in download_task(self, task_id)
    717             except (URLError, UnicodeEncodeError) as e:
    718                 print(e)
--> 719                 raise e
    720 
    721             # Cache the xml task file

HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by mfeurer** [comment] 2016-02-12 11:46
Can the package actually check the API key? If yes, this particular problem can be solved. Nevertheless, I think the problem is on the server side. The API only shows the error it gets from the server and 500 is the wrong error for not being authenticated.

**Comment by amueller** [comment] 2016-03-18 15:11
fixed by raising a value error containing the xml if the return is not  200

**Closed** 2016-03-18 15:10 UTC
