### ISSUE TITLE
run.get_predictions() convenience function

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#1114] opened 2021-09-16 09:44 UTC
#### Description
To access the prediction of a run, I believe we currently have to manually retrieve and parse the prediction file.

#### Steps/Code to Reproduce
See Colab notebook here:
https://colab.research.google.com/drive/17R22tmfAe00uBRNKik-_uam7BGSCOMbS#scrollTo=7qOHbWuhoTWq

#### Expected Results
A convenience function that returns a numpy array or dataframe directly.
Maybe the code in the notebook above is helpful for this.

**Comment by PGijsbers** [comment] 2021-09-16 13:16
Duplicate of #1103.

**Closed by PGijsbers** 2021-09-16 13:16 UTC
Labels: enhancement
