### ISSUE TITLE
sklearn converter can't handle BaseSearchCV evaluation metrics

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#496] opened 2018-07-27 22:22 UTC
The following code yields the following error

code
```
import openml
import sklearn

from sklearn.model_selection._search import RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier

scorer = sklearn.metrics.make_scorer(sklearn.metrics.accuracy_score)
estimator = RandomizedSearchCV(DecisionTreeClassifier(), {'min_samples_leaf': [1, 2, 3]}, n_iter=2, scoring=scorer)

openml.flows.sklearn_to_flow(estimator)
```

error:
```
/home/janvanrijn/anaconda3/envs/openml-defaults/bin/python /home/janvanrijn/projects/openml-defaults/jan_test.py
Traceback (most recent call last):
  File "/home/janvanrijn/projects/openml-defaults/jan_test.py", line 10, in <module>
    openml.flows.sklearn_to_flow(estimator)
  File "/home/janvanrijn/projects/openml-python/openml/flows/sklearn_converter.py", line 43, in sklearn_to_flow
    rval = _serialize_model(o)
  File "/home/janvanrijn/projects/openml-python/openml/flows/sklearn_converter.py", line 196, in _serialize_model
    _extract_information_from_model(model)
  File "/home/janvanrijn/projects/openml-python/openml/flows/sklearn_converter.py", line 304, in _extract_information_from_model
    rval = sklearn_to_flow(v, model)
  File "/home/janvanrijn/projects/openml-python/openml/flows/sklearn_converter.py", line 82, in sklearn_to_flow
    raise TypeError(o, type(o))
TypeError: (make_scorer(accuracy_score), <class 'sklearn.metrics.scorer._PredictScorer'>)
```

Apparently, the scorer can only be set to None, in which case the default scorer from the estimator will be used (which can potentially be anything, depending on the classifier)

**Comment by mfeurer** [comment] 2018-07-30 06:14
Closing this, it is a duplicate of #288.

**Closed by mfeurer** 2018-07-30 06:14 UTC
