### ISSUE TITLE
Can't submit BaggingClassifier with base_estimator param

### ISSUE THREAD

**Issue by heytitle** [openml/openml-python#122] opened 2016-04-17 14:49 UTC
I'm trying to use `BaggingClassifier` for task `14951`, but the error below occurrs  

```
Traceback (most recent call last):
  File "temp.py", line 14, in <module>

  File "/usr/local/lib/python2.7/site-packages/openml-0.2.1-py2.7.egg/openml/runs/run.py", line 85, in publish
    "/run/", file_elements=data)
  File "/usr/local/lib/python2.7/site-packages/openml-0.2.1-py2.7.egg/openml/_api_calls.py", line 39, in _perform_api_call
    file_elements=file_elements)
  File "/usr/local/lib/python2.7/site-packages/openml-0.2.1-py2.7.egg/openml/_api_calls.py", line 70, in _read_url_files
    raise OpenMLServerError(response.text)
openml.exceptions.OpenMLServerError: OpenML Server error: <oml:error xmlns:oml="http://openml.org/openml">
    <oml:code>213</oml:code>
    <oml:message>Parameter in run xml unknown</oml:message>
    </oml:error>
```

Here is the code that I use and it s mostly copied from http://www.openml.org/guide#!python.

```
from openml import tasks,runs

from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier

# Download task, run learner, publish results
task = tasks.get_task(14951)

clf= BaggingClassifier( base_estimator=KNeighborsClassifier(), n_estimators=100 )

run = runs.run_task(task, clf)

return_code, response = run.publish()

if(return_code == 200):
    response_dict = xmltodict.parse(response)
    run_id = response_dict['oml:upload_run']['oml:run_id']
    print("Uploaded run with id %s. Check it at www.openml.org/r/%s" % (run_id,run_id))

```

**Comment by joaquinvanschoren** [comment] 2016-04-18 09:47
I'm guessing that this happens because complex classifiers and pipelines are not fully supported yet. At least the OpenML error indicates that the algorithm was not properly registered.

**Comment by amueller** [comment] 2016-04-18 16:18
sorry, my bad probably. I can check it out in a week or so (feel free to ping me again).

**Comment by mfeurer** [comment] 2016-09-14 16:15
Sorry, this will take some more time. First we need to finish #167. After that we need to write code which can upload the parameter setting for nested predictions (a rewrite of run_task).

**Comment by janvanrijn** [comment] 2017-02-01 20:41
I think is issue is outdated (can't reproduce.)

The aforementioned code (in openml/guide) is outdated too. I have updated this. 

Issue can be closed IMO

**Comment by mfeurer** [comment] 2017-02-02 11:44
@janvanrijn added a test to cover this case. I'm closing it now. @heytitle if this happens again (so far only on the test server) please reopen.

**Closed by mfeurer** 2017-02-02 11:44 UTC
Labels: bug
